export const actionsEnum = {
  FETCH_CONSTRAINTS_REQUEST: 'FETCH_CONSTRAINTS_REQUEST',
  FETCH_CONSTRAINTS_SUCCESS: 'FETCH_CONSTRAINTS_SUCCESS',
  FETCH_CONSTRAINTS_FAILURE: 'FETCH_CONSTRAINTS_FAILURE',
  FETCH_OFFER_REQUEST: 'FETCH_OFFER_REQUEST',
  FETCH_OFFER_SUCCESS: 'FETCH_OFFER_SUCCESS',
  FETCH_OFFER_FAILURE: 'FETCH_OFFER_FAILURE',
};
